# Generated by Django 4.0.4 on 2022-05-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0015_project_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='description_code',
        ),
    ]
