# Generated by Django 4.0.4 on 2022-05-05 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0016_rename_description_project_description_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='code',
            new_name='about_project',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description_code',
            new_name='description_write_code',
        ),
    ]
