# Generated by Django 4.0.4 on 2022-05-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0017_rename_code_project_about_project_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description_write_code',
            new_name='write_code',
        ),
    ]
