# Generated by Django 4.0.4 on 2022-05-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproject', '0018_rename_description_write_code_project_write_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='img',
            field=models.ImageField(default='photos/comment.png', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
